<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AssemblyName>Show-OpStatus</AssemblyName>
    <RootNamespace>Show_OpStatus</RootNamespace>
  </PropertyGroup>
</Project>